In [6]:
import numpy as np
list1=[1,2,3,4]
list2=[4,5,6,7]
arr = np.array([list1,list2])
arr.shape
list3=[24,26,37,48]
list4=[41,52,61,70]
arr1 = np.array([list3,list4])

In [13]:
res = arr+arr1
res

array([[3, 5],
       [7, 9]])

In [9]:
list1=[2,3]
list2=[4,5]
arr = np.array([list1,list2])
arr.shape
list3=[1,2,]
list4=[3,4]
arr1 = np.array([list3,list4])

In [10]:
t = arr*arr1
t

array([[ 2,  6],
       [12, 20]])

In [20]:
list7 = [56,34]
list3=[78,90]
arr2=np.array([list7,list3])
k=arr2.transpose()
k

array([[56, 78],
       [34, 90]])

In [39]:
p=['a','c','d']
g=p.sort()
print(g)

None


In [41]:
str = input("Enter any sentence: ")
words = [word.lower() for word in str.split()]
words.sort()
print("The sorted words are:")
for word in words:
   print(word)

Enter any sentence: My name is Akash Borgalli
The sorted words are:
akash
borgalli
is
my
name


In [70]:
def Punctuation(newstring):
  punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
  for i in newstring.lower():
    if i in punctuations:
        newstring = newstring.replace(i, "")
  print(newstring)
string = "A*k*a@s!h #is$% g%#o#o^d# $%b^o&y"
Punctuation(string)

Akash is good boy
