In [27]:
import numpy as np
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
sum=0
for i in arr:
    sum=sum+i
print(sum)
    

45


In [5]:
arr.argmax()

9

In [10]:
lst=[24,56,78]
lst2=[90,78,34]
arr1 =np.array([lst,lst2])
arr1

array([[24, 56, 78],
       [90, 78, 34]])

In [11]:
np.rot90(arr1)

array([[78, 34],
       [56, 78],
       [24, 90]])

In [28]:
arr2=np.array_split(arr,3)

In [29]:
t=arr2
arr2

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [26]:
t.reverse()
t

[array([7, 8, 9]), array([4, 5, 6]), array([0, 1, 2, 3])]

In [31]:
def monotonic(array):
    decreasing=False
    if (array[0] > array[1]):
        decreasing = True
    for i in range(len(array)-1):
        if (array[i]<array[i+1] and decreasing or array[i]>arr[i+1] and not decreasing):
            return False
    return True

In [33]:
print(monotonic([1,2,3,4,8]))
print(monotonic([1,2,3,5,4,6]))
print(monotonic([10,9,8,7,6]))

True
False
True
